name: PR-check

on:
    pull_request:
        branches:
            - main

jobs:
    ts-compiler:
        name: TSC
        runs-on: ubuntu-slim

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Node
              uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun install

            - name: Check compiler
              run: bun run check

    lint:
        name: Linting
        runs-on: ubuntu-slim

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Node
              uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun install

            - name: Check linting
              run: bun run lint
